# Generated by Django 3.1.7 on 2021-04-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210405_0324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
