# Generated by Django 3.1.7 on 2021-03-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_db', '0003_auto_20210328_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='womenshirtsproducts',
            name='check',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
