# Generated by Django 3.1.7 on 2021-03-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_db', '0005_remove_womenshirtsproducts_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='womenshirtsproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
