# Generated by Django 3.1.7 on 2021-04-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_db', '0010_auto_20210404_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='Mans_DressShirts_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_db.mandressshirtsproducts'),
        ),
    ]
