# Generated by Django 3.1.7 on 2021-04-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_db', '0014_auto_20210405_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
