# Generated by Django 3.1.7 on 2021-04-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_db', '0016_comment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
    ]
